services:
  - type: web
    name: url-shortener
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: NEXT_PUBLIC_BASE_URL
        sync: false
